### ISSUE TITLE
Error during linking stage

### ISSUE THREAD

**Issue by wreckdump** [tobac-project/tobac#385]
I am getting the following message during the linking stage.

```
Traceback (most recent call last):
  File "/home/rangke/work/thesis/py.scr/trk.fet.seg.lnk.py", line 128, in <module>
    trk               =  tobac.tracking.linking_trackpy(fet_var, tb, dt=dt, dxy=dxy, **param_lnk)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rangke/py.vrt/lib/python3.11/site-packages/tobac/tracking.py", line 343, in linking_trackpy
    trajectories_unfiltered = tp.link(
                              ^^^^^^^^
  File "/home/rangke/py.vrt/lib/python3.11/site-packages/trackpy/linking/linking.py", line 192, in link
    for i, _ids in link_iter(coords_iter, search_range, **kwargs):
  File "/home/rangke/py.vrt/lib/python3.11/site-packages/trackpy/linking/linking.py", line 88, in link_iter
    val = next(coords_iter)
          ^^^^^^^^^^^^^^^^^
  File "/home/rangke/py.vrt/lib/python3.11/site-packages/trackpy/linking/utils.py", line 53, in coords_from_df
    for time in range(unique_times[0], unique_times[-1] + 1):
                      ~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I don't quite understand what the error is complaining about.

The following are the settings that I am using for feature detection, segmentation and linking process.

```
   # feature detection
   param_fet={}
   param_fet['target']='minimum'
   param_fet['threshold']=[thres]
   param_fet['n_min_threshold']=4
   param_fet['position_threshold']='center'
   param_fet['sigma_threshold']=0.5
   param_fet['PBC_flag'] = 'hdim_2'
   
   fet               =  tobac.feature_detection.feature_detection_multithreshold(tb, dxy, **param_fet)

   
   # segmentation
   param_seg={}
   param_seg['target']='minimum'
   param_seg['method']='watershed'
   param_seg['threshold']=thres
   param_seg['PBC_flag'] = 'hdim_2'
    
   msk_var, fet_var  =  tobac.segmentation.segmentation_2D(fet, tb, dxy, **param_seg)
      
   param_lnk={}
   param_lnk['v_max']=None
   param_lnk['d_max']=111.0e3*1 # 10 degrees in meters
   param_lnk['stubs']=1
   param_lnk['order']=2
   param_lnk['extrapolate']=0
   param_lnk['memory']=0
   param_lnk['adaptive_stop']=0.5
   param_lnk['adaptive_step']=0.95
   param_lnk['subnetwork_size']=10
   param_lnk['method_linking']= 'random'
   param_lnk['PBC_flag'] = 'hdim_2'
   param_lnk['min_h2'] = 0
   param_lnk['max_h2'] = 1440
      
   trk               =  tobac.tracking.linking_trackpy(fet_var, tb, dt=dt, dxy=dxy, **param_lnk)
```

**Comment by wreckdump** [comment]
Found the issue. Missing value is set to unpreferred value.
